# Generated by Django 3.0.5 on 2020-05-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='files/pdfs/', verbose_name='Attachment'),
        ),
    ]
