# Generated by Django 3.0.5 on 2020-06-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200601_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='C:\\VSCODE\\django\\snapnote_venv\\snapnote_django\\snapnote', verbose_name='File'),
        ),
    ]
