# Generated by Django 3.0.5 on 2020-06-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200606_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='files/pdfs/', verbose_name='File'),
        ),
    ]
